# (c) 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
# file or any portion thereof may not be reproduced or used in any manner
# whatsoever without the express written permission of KAI OS TECHNOLOGIES
# (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
# LIMITED or its affiliate company and may be registered in some jurisdictions.
# All other trademarks are the property of their respective owners.

variables: &global_variables
  GIT_DEPTH: 1

.global_setup: &global_setup
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - git config --global url."${CI_SERVER_URL}/".insteadOf "git@${CI_SERVER_HOST}:"
  - '[ "$(cat ${HOME}/.mozbuild/ver)" = "1" ] || curl https://packages.preprod.kaiostech.com/ndk/mozbuild.tar.bz2 | tar -C ${HOME}/ -xj'

stages:
  - build

build:desktop:
  before_script:
    - *global_setup
  variables:
    <<: *global_variables
    DEFAULT_DESKTOP_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/desktop:latest"
    MOZ_OBJDIR: 'objdir-desktop-gecko'
    MOZCONFIG: 'mozconfig-b2g-desktop'
  image: $DEFAULT_DESKTOP_DOCKER_IMAGE
  stage: build
  tags:
    - gecko-dev
  script:
    - ./mach build
    - ./mach package
  artifacts:
    expire_in: 1 week
    paths:
      - "objdir-desktop-gecko/dist/b2g-*"

build:desktop-koost:
  before_script:
    - *global_setup
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/koost.git -b next > /dev/null 2>&1
  variables:
    <<: *global_variables
    DEFAULT_DESKTOP_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/desktop:latest"
    MOZ_OBJDIR: 'objdir-desktop-gecko-koost'
    MOZCONFIG: 'mozconfig-b2g-desktop'
  image: $DEFAULT_DESKTOP_DOCKER_IMAGE
  stage: build
  tags:
    - gecko-dev
  script:
    - ./mach build
    - ./mach package
  artifacts:
    expire_in: 1 week
    paths:
      - "objdir-desktop-gecko-koost/dist/b2g-*"

build:arm:
  before_script:
    - *global_setup
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/koost.git -b next > /dev/null 2>&1
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/dummy/gonk-q.git > /dev/null 2>&1
  variables:
    <<: *global_variables
    DEFAULT_ARM_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    GONK_PATH: "${CI_PROJECT_DIR}/gonk-q"
    GECKO_OBJDIR: "${CI_PROJECT_DIR}/objdir-arm-gecko"
    GONK_PRODUCT_NAME: msm8937_32go
    GET_FRAMEBUFFER_FORMAT_FROM_HWC: 1
    PLATFORM_VERSION: 29
    TARGET_ARCH: arm
    TARGET_ARCH_VARIANT: armv8-a
    TARGET_CPU_VARIANT: cortex-a53
    ANDROID_NDK: '~/.mozbuild/android-ndk-r20b-canary'
    PRODUCT_MANUFACTURER: QUALCOMM
  image: $DEFAULT_ARM_DOCKER_IMAGE
  stage: build
  tags:
    - gecko-dev
  script:
    - ./build-b2g.sh
    - ./build-b2g.sh package
  artifacts:
    expire_in: 2 week
    paths:
      - "objdir-arm-gecko/dist/b2g-*"
      - "push-b2g.sh"
